version: 2
updates:
  -
    package-ecosystem: github-actions
    directory: /
    target-branch: next
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Berlin
    assignees:
      - novusvetus
    reviewers:
      - novusvetus
    labels:
      - maintenance
      - dependencies
    open-pull-requests-limit: 10
  -
    package-ecosystem: npm
    directory: /
    target-branch: next
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Berlin
    assignees:
      - novusvetus
    reviewers:
      - novusvetus
    labels:
      - maintenance
      - dependencies
    open-pull-requests-limit: 10
